name: Linux build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container: jjmerelo/alpine-raku:latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Raku version
      run: raku -v

    - name: Install dependencies
      run: zef install --deps-only .

    - name: Run tests
      run: zef test --verbose .
